#FROM sharmaatul11/fsl502py369ltx-full:latest
FROM sharmaatul11/yashengstep1withfsl:latest
RUN apt update
COPY scct_strippedResampled1.nii.gz   /templatenifti/
COPY  midlinecssfResampled1.nii.gz   /templatemasks/
RUN mkdir -p /callfromgithub
RUN chmod 755 /callfromgithub
COPY downloadcodefromgithub.sh /callfromgithub/
RUN chmod +x /callfromgithub/downloadcodefromgithub.sh
RUN chmod +x /Stroke_CT_Processing/*.sh
RUN cp -r  /usr/share/fsl/5.0/* /usr/lib/fsl/5.0/
RUN chmod 755 /Stroke_CT_Processing
RUN for x in  /Stroke_CT_Processing/*/* ; do chmod +x $x ; done
RUN for x in  /Stroke_CT_Processing/* ; do chmod +x $x ; done
RUN apt install -y \
  vim  \
  zip  \
  unzip  \
  curl  \
  git \
  tree
RUN pip3 install \
  nibabel  \
  numpy  \
  xmltodict  \
  pandas  \
  requests  \
  pydicom  \
  python-gdcm  \
  glob2  \
  scipy  \
  pypng  \
  PyGithub
